version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: github.com/yagoayala/go-rest-api
    container_name: go-rest-api
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/go-rest-api
    volumes:
      - go-rest-api:/var/lib/postgresql/data

volumes:
  go-rest-api: